version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greetings from Sample App
          command: echo Sample App.

      - run:
          name: Print the Current Time
          command: date
  test:
    requires:
      - build
    docker:
      - image: circleci/node:8.9.2
    steps:
      - checkout
      - run: npm install
      - run: mkdir ~/junit
      - run:
          command: karma start ./karma.conf.js
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always  
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test