version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greetings from Sample App
          command: echo Sample App.

      - run:
          name: Print the Current Time
          command: date
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: ng test
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
