version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greetings from Sample App
          command: echo Sample App.

      - run:
          name: Print the Current Time
          command: date
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: npm install
      - run: sudo npm install -g karma
      - run: sudo npm install karma-spec-reporter
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
